from bokeh.plotting import figure, show, save, ColumnDataSource, output_file
from bokeh.io import export_svgs
from bokeh.models import LinearColorMapper, HoverTool
from bokeh.transform import transform
from bokeh.util.hex import hexbin

import pandas as pd

data = pd.read_csv("data/patents_in_cosmonautics.csv")

data = data.sort_values("count")

data['size'] = (data['count']**.7)+15
c = ColumnDataSource(pd.DataFrame(data.to_records()))

countries = data['country'].unique()
years = data['year'].unique()

hover = HoverTool(tooltips=[
    ("Anzahl", "@count"),
    ("Land", "@country"),
    ("Datum", "@year")
])
p = figure(
    width=1800,
    height=800,
    y_range=countries,
    tools=[hover]
)


# generated by https://mycolor.space/?hex=%23845EC2&sub=1
colors = ['#EB1A5F', '#C43286', '#8E4897', '#585191', '#335078', '#2F4858'][::-1]

mapper = LinearColorMapper(
    palette=colors,
    low=min(data['count']**.5),
    high=max(data['count']**.5)
)

p.rect(x="year", y="country", width=1, height=1, source=c, fill_color=transform('count', mapper))

show(p)
